before_commands:
- "composer install --dev"

tools:
external_code_coverage: true

build:     
    environment:
        php:
            version: 7.0.8
filter:
    paths: ["src/*"]
    excluded_paths:
    - "*/Tests/*"
